Bank Loan Analysis Report

Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
df = pd.read_excel('C:/Users/91738/Downloads/financial_loan_data_excel.xlsx')

In [3]:
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [4]:
df.tail()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,2021-07-11,2021-05-16,2021-05-16,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,2021-10-11,2021-04-16,2021-05-16,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,2021-09-11,2021-05-16,2021-05-16,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,2021-10-11,2021-05-16,2021-05-16,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,2021-07-11,2021-05-16,2021-05-16,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

Import MetaData of Data

In [5]:
print("No of Rows:",df.shape[0])

No of Rows: 38576

In [6]:
print("No of Columns:",df.shape[1])

No of Columns: 24

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB

In [8]:
df.describe()

,id,issue_date,last_credit_pull_date,last_payment_date,next_payment_date,member_id,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,38576,3.857600e+04,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.810371e+05,2021-07-16 02:31:35.562007040,2021-06-08 13:36:34.193280512,2021-06-26 09:52:08.909166080,2021-07-26 20:42:20.605557760,8.476515e+05,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
min,5.473400e+04,2021-01-01 00:00:00,2021-01-08 00:00:00,2021-01-08 00:00:00,2021-02-08 00:00:00,7.069900e+04,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,2021-04-11 00:00:00,2021-04-15 00:00:00,2021-03-16 00:00:00,2021-04-16 00:00:00,6.629788e+05,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,2021-07-11 00:00:00,2021-05-16 00:00:00,2021-06-14 00:00:00,2021-07-14 00:00:00,8.473565e+05,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,2021-10-11 00:00:00,2021-08-13 00:00:00,2021-09-15 00:00:00,2021-10-15 00:00:00,1.045652e+06,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000
max,1.077501e+06,2021-12-12 00:00:00,2022-01-20 00:00:00,2021-12-15 00:00:00,2022-01-15 00:00:00,1.314167e+06,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000,58564.000000
std,2.113246e+05,NaN,NaN,NaN,NaN,2.668105e+05,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777

Data Types

In [9]:
df.dtypes

id                                int64
address_state                    object
application_type                 object
emp_length                       object
emp_title                        object
grade                            object
home_ownership                   object
issue_date               datetime64[ns]
last_credit_pull_date    datetime64[ns]
last_payment_date        datetime64[ns]
loan_status                      object
next_payment_date        datetime64[ns]
member_id                         int64
purpose                          object
sub_grade                        object
term                             object
verification_status              object
annual_income                   float64
dti                             float64
installment                     float64
int_rate                        float64
loan_amount                       int64
total_acc                         int64
total_payment                     int64
dtype: object

Analysis

Total Loan Applications

In [10]:
total_loan_applications = df['id'].count()
print("Total Loan Applications:",total_loan_applications)

Total Loan Applications: 38576

MTD Total Loan Applications

In [11]:
latest_issue_date = df['issue_date'].max()
latest_issue_year = latest_issue_date.year
latest_issue_month = latest_issue_date.month
mtd_data = df[(df['issue_date'].dt.year == latest_issue_year) & (df['issue_date'].dt.month == latest_issue_month)]
mtd_loan_applications = mtd_data['id'].count()
print(f"Total Loan Applications for {latest_issue_date.strftime('%B%Y')}:",mtd_loan_applications)

Total Loan Applications for December2021: 4314

Total Funded Amount

In [12]:
total_funded_amount = df['loan_amount'].sum()
print("Total Funded Amount:",round(total_funded_amount/1000000,2),"millions")

Total Funded Amount: 435.76 millions

MTD Total Funded Amount

In [13]:
latest_issue_date = df['issue_date'].max()
latest_issue_year = latest_issue_date.year
latest_issue_month = latest_issue_date.month
mtd_data = df[(df['issue_date'].dt.year == latest_issue_year) & (df['issue_date'].dt.month == latest_issue_month)]
mtd_funded_amount = mtd_data['loan_amount'].sum()
print(f"Total Funded Amount for {latest_issue_date.strftime("%B %Y")}:",round((mtd_funded_amount/1000000),2),"millions")

Total Funded Amount for December 2021: 53.98 millions

Total Amount Received

In [14]:
total_amount = df['total_payment'].sum()
print("Total Amount Funded:",round(total_amount/1000000,2),"millions")

Total Amount Funded: 473.07 millions

MTD Total Amount Received

In [15]:
latest_issue_date = df['issue_date'].max()
latest_issue_year = latest_issue_date.year
latest_issue_month = latest_issue_date.month
mtd_data = df[(df['issue_date'].dt.year == latest_issue_year) & (df['issue_date'].dt.month == latest_issue_month)]
mtd_amount = mtd_data['total_payment'].sum()
print(f"Total Funded Amount for {latest_issue_date.strftime("%B %Y")}:",round((mtd_amount/1000000),2),"millions")

Total Funded Amount for December 2021: 58.07 millions

Average Interest Rate

In [16]:
avg_interest_rate = df['int_rate'].mean()
print("Average Interest Rate:",round(avg_interest_rate,2),"%")

Average Interest Rate: 0.12 %

Average Debt to Income Ratio(DTI)

In [17]:
avg_dti_rate = df['dti'].mean() * 100
print("Average DTI Rate:",round(avg_dti_rate,2),"%")

Average DTI Rate: 13.33 %

Good Loan Metrics

In [18]:
good_loans = df[df['loan_status'].isin(['Fully Paid','Current'])]
total_loan_applications = df['id'].count()
good_loan_applications = good_loans['id'].count()
good_loan_funded_amount = good_loans['loan_amount'].sum()
good_loan_received_amount = good_loans['total_payment'].sum()
good_loan_percentage = (good_loan_applications / total_loan_applications) * 100

print("Good Loan Applications:",good_loan_applications)
print("Good Loan Funded Amount:",round(good_loan_funded_amount/1000000,2),"millions")
print("Good Loan Funded Amount:",round(good_loan_received_amount/1000000,2),"millions")
print("Percentage of Good Loan Applications:",round(good_loan_percentage,2),"%")

Good Loan Applications: 33243
Good Loan Funded Amount: 370.22 millions
Good Loan Funded Amount: 435.79 millions
Percentage of Good Loan Applications: 86.18 %

Bad Loan Metrics

In [19]:
bad_loans = df[df['loan_status'].isin(['Charged Off'])]
total_loan_applications = df['id'].count()
bad_loan_applications = bad_loans['id'].count()
bad_loan_funded_amount = bad_loans['loan_amount'].sum()
bad_loan_received_amount = bad_loans['total_payment'].sum()
bad_loan_percentage = (bad_loan_applications / total_loan_applications) * 100

print("Bad Loan Applications:",bad_loan_applications)
print("Bad Loan Funded Amount:",round(bad_loan_funded_amount/1000000,2),"millions")
print("Bad Loan Funded Amount:",round(bad_loan_received_amount/1000000,2),"millions")
print("Percentage of Bad Loan Applications:",round(bad_loan_percentage,2),"%")

Bad Loan Applications: 5333
Bad Loan Funded Amount: 65.53 millions
Bad Loan Funded Amount: 37.28 millions
Percentage of Bad Loan Applications: 13.82 %